### ISSUE TITLE
[mlflow] The readiness probe and liveness probe need to be configurable

### ISSUE THREAD

**Issue by subramaniam20jan** [community-charts/helm-charts#16]
### Is your feature request related to a problem ?

When you start mlflow behind a proxy, you often do not want to serve it on root. This means that you configure mlflow with --static-prefix and ensure it is served with a prefix mentioned.

The way the chart is designed right now, it allows for the mlflow server to be started up with this extra argument, but the readiness probe and liveness probe arent configurable to use the new prefix added to the mlflow server.

### Describe the solution you'd like.

Parameterize the readiness probe and liveness probe path in the deployment to ensure it can be configured by users of the chart.

### Describe alternatives you've considered.

NONE

**Comment by burakince** [comment]
Hi @subramaniam20jan 

Yes, good point. Let me write a unit test about it. I think the implementation should be very easy.

**Comment by burakince** [comment]
Hi @subramaniam20jan 

The mlflow chart version 0.2.7 should solve the problem. Also, I added [an example of static prefix usage to here](https://github.com/community-charts/examples/tree/main/mlflow-examples/static-prefix-example). If it doesn't solve the problem, please feel free to reopen this issue.

Best,
Burak
