### ISSUE TITLE
[mlflow] Extra args broken

### ISSUE THREAD

**Issue by subramaniam20jan** [community-charts/helm-charts#18]
### Describe the bug a clear and concise description of what the bug is.

The new staticPrefix argument being under extraArgs breaks the chart for users that need to use the extraArgs

### What's your helm version?

version.BuildInfo{Version:"v3.8.1", GitCommit:"5cb9af4b1b271d11d7a97a71df3ac337dd94ad37", GitTreeState:"clean", GoVersion:"go1.17.8"}

### What's your kubectl version?

Client Version: version.Info{Major:"1", Minor:"22", GitVersion:"v1.22.5", GitCommit:"5c99e2ac2ff9a3c549d9ca665e7bc05a3e18f07e", GitTreeState:"clean", BuildDate:"2021-12-16T08:38:33Z", GoVersion:"go1.16.12", Compiler:"gc", Platform:"darwin/arm64"} Server Version: version.Info{Major:"1", Minor:"23", GitVersion:"v1.23.3", GitCommit:"816c97ab8cff8a1c72eccca1026f7820e93e0d25", GitTreeState:"clean", BuildDate:"2022-01-25T21:19:12Z", GoVersion:"go1.17.6", Compiler:"gc", Platform:"linux/arm64"}

### Which chart?

mlflow

### What's the chart version?

0.2.7

### What happened?

The newly added staticPrefix parameter under extraArgs breaks the chart when used because it tries to add an extra argument to the mlflow server command that doesnt exist.

### Enter the command that you execute and failing/misfunctioning.

helm install -f mlflow/values.yaml mlflow ./mlflow/

### Anything else we need to know?

I am just creating a pull request to address this in a bit different way and havent tested it yet. Just wanted to create a request to highlight a solution.

You could also handle the staticPrefix as a separate argument in the extraEnv when starting up the mlflow server to make this work smoother for a final user, but this solution should work as well.

**Comment by burakince** [comment]
Hi @subramaniam20jan 

Could you please share your values.yaml file with me? Do you have any additional change in it?

**Comment by burakince** [comment]
Hi @subramaniam20jan 

I really didn't understand the problem. Static prefix is valid argument for mlflow server. You can find more information [here](https://mlflow.org/docs/latest/cli.html#cmdoption-mlflow-server-static-prefix).

Also, it tested with argument and without argument in [the unit tests](https://github.com/community-charts/helm-charts/blob/main/charts/mlflow/unittests/deployment_test.yaml#L65). Also, it tested without argument in the integration test which we run it with [kind here](https://github.com/community-charts/helm-charts/runs/7283774204?check_suite_focus=true#step:12:175).

I'm really not able to recreate the issue. Could you please share the error message?

**Comment by burakince** [comment]
Well, if you use `mlflow ui` command, you must change it to `mlflow server` command for production usage. You can find same explanation from here: https://mlflow.org/docs/latest/cli.html#mlflow-ui

**Comment by subramaniam20jan** [comment]
Actually it was my bad. This wasnt really an issue but I appreciate the addition of the extra parameters to the readiness and liveness probe :)

**Comment by subramaniam20jan** [comment]
btw, @burakince great job on the chart and image! I was something I have made many times in individual assignments and missed having in open source somewhere. Came across your project when I was about to create one myself. Saves me a lot of work :)
