### ISSUE TITLE
[mlflow] Use port name instead of port number in ServiceMonitor 

### ISSUE THREAD

**Issue by mikwieczorek** [community-charts/helm-charts#22]
### Describe the bug a clear and concise description of what the bug is.

First of all, thanks to everyone creating this Helm Chart as it is really good and easy to use.

However, I encountered a problem when choosing to include ServiceMonitor and Prometheus metrics along the Deployment. Generally, the created ServiceMonitor for MLFlow is correct, yet in the current form it does not work for me.
I use the latest Prometheus deployed using the official Helm Chart and the MLFlow metrics did not show up in the Targets, yet it was visible in Service Discovery panel in Prometheus Dashboard, but appeared as `0/1 active targets`.

After a couple of hours of educated debugging I changed manually the `targetPort: 80` to `port: http` in the deployed ServiceMonitor manifest. It worked straightaway! 

What I propose is a simple fix:
According to official Prometheus Troubleshooting docs the port specified in ServiceMonitor should use `name` instead of port number ([Link to docs](https://github.com/prometheus-operator/prometheus-operator/blob/main/Documentation/troubleshooting.md#using-textual-port-number-instead-of-port-name)) 
Simple fix would be to change `targetPort: 80` to `port: http` in `templates/servicemonitor.yaml`. Port name `http` is already hardcoded, so can be used directly or new parameter could be introduced to give the freedom to choose port name.
I am aware that port number of type Integer should also work...

### What's your helm version?

3.6.0

### What's your kubectl version?

1.19

### Which chart?

mlflow

### What's the chart version?

0.2.21

### Enter the command that you execute and failing/misfunctioning.

 helm install --namespace mlflow mlflow-tracking-server community-charts/mlflow --set serviceMonitor.enabled=true

**Comment by burakince** [comment]
Well, it looks like your link refers to the port (service port) rather than targetPort (pod's port. This is currently what we use.). But we can even make it optional (port or targetPort selection) and use a name rather than a port number. It looks like it works with the latest version of Prometheus but I think we need to support all versions together.

And [this is the full schema of endpoints field](https://github.com/prometheus-operator/prometheus-operator/blob/main/Documentation/api.md#monitoring.coreos.com/v1.Endpoint).

I will do some additional manual tests and send the PR.

**Comment by burakince** [comment]
Hi @mikwieczorek 

Chart version 0.3.0 should solve your problem. If it still accrues, feel free to reopen this issue. You can use the following command to update your deployment without the need for additional changes.

```
helm repo update
helm upgrade --install --namespace mlflow mlflow-tracking-server community-charts/mlflow --set serviceMonitor.enabled=true
```

Best,
Burak

**Comment by mikwieczorek** [comment]
Thank you @burakince for your prompt fix. It works correctly after the update. 
Next time, I will make an MR instead of just reporting the issue
